spring.application.name=booklist
# H2 DATABASE CONFIGURATION
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.datasource.url=jdbc:h2:mem:testdb
# SHOW GENERATED SQL
spring.jpa.show-sql=true
